site_name: OpenCode Go Kit
site_description: Documentation and API Reference for the OpenCode Go Kit client wrapper.

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Scheme toggle to switch between light and dark modes
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Welcome: index.md
  - API Reference: api.md
