package api

// Code generated by tools/generator; DO NOT EDIT.

import (
	"context"

	"github.com/dakolli/opencode-go-kit/pkg/client"

	"github.com/go-faster/jx"
)

// AppAgents invokes app.agents operation.
//
// Get a list of all available AI agents in the OpenCode system.
//
// GET /agent
func (a *API) AppAgents(
	ctx context.Context,
	params client.AppAgentsParams,
	options ...client.RequestOption,
) ([]client.Agent, error) {
	res, err := Extract[*client.AppAgentsOKApplicationJSON](a.Client.AppAgents(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Agent(*res), nil
}

// AppSkills invokes app.skills operation.
//
// Get a list of all available skills in the OpenCode system.
//
// GET /skill
func (a *API) AppSkills(
	ctx context.Context,
	params client.AppSkillsParams,
	options ...client.RequestOption,
) ([]client.AppSkillsOKItem, error) {
	res, err := Extract[*client.AppSkillsOKApplicationJSON](a.Client.AppSkills(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.AppSkillsOKItem(*res), nil
}

// CommandList invokes command.list operation.
//
// Get a list of all available commands in the OpenCode system.
//
// GET /command
func (a *API) CommandList(
	ctx context.Context,
	params client.CommandListParams,
	options ...client.RequestOption,
) ([]client.Command, error) {
	res, err := Extract[*client.CommandListOKApplicationJSON](a.Client.CommandList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Command(*res), nil
}

// ConfigProviders invokes config.providers operation.
//
// Get a list of all configured AI providers and their default models.
//
// GET /config/providers
func (a *API) ConfigProviders(
	ctx context.Context,
	params client.ConfigProvidersParams,
	options ...client.RequestOption,
) (*client.ConfigProvidersOK, error) {
	return Extract[*client.ConfigProvidersOK](a.Client.ConfigProviders(ctx, params, options...))
}

// ExperimentalCapabilitiesGet invokes experimental.capabilities.get operation.
//
// Get experimental features enabled on the OpenCode server.
//
// GET /experimental/capabilities
func (a *API) ExperimentalCapabilitiesGet(
	ctx context.Context,
	params client.ExperimentalCapabilitiesGetParams,
	options ...client.RequestOption,
) (*client.ExperimentalCapabilities, error) {
	return Extract[*client.ExperimentalCapabilities](a.Client.ExperimentalCapabilitiesGet(ctx, params, options...))
}

// ExperimentalConsoleGet invokes experimental.console.get operation.
//
// Get the active Console org name and the set of provider IDs managed by that Console org.
//
// GET /experimental/console
func (a *API) ExperimentalConsoleGet(
	ctx context.Context,
	params client.ExperimentalConsoleGetParams,
	options ...client.RequestOption,
) (*client.ConsoleState, error) {
	return Extract[*client.ConsoleState](a.Client.ExperimentalConsoleGet(ctx, params, options...))
}

// ExperimentalConsoleListOrgs invokes experimental.console.listOrgs operation.
//
// Get the available Console orgs across logged-in accounts, including the current active org.
//
// GET /experimental/console/orgs
func (a *API) ExperimentalConsoleListOrgs(
	ctx context.Context,
	params client.ExperimentalConsoleListOrgsParams,
	options ...client.RequestOption,
) (*client.ExperimentalConsoleListOrgsOK, error) {
	return Extract[*client.ExperimentalConsoleListOrgsOK](a.Client.ExperimentalConsoleListOrgs(ctx, params, options...))
}

// ExperimentalConsoleSwitchOrg invokes experimental.console.switchOrg operation.
//
// Persist a new active Console account/org selection for the current local OpenCode state.
//
// POST /experimental/console/switch
func (a *API) ExperimentalConsoleSwitchOrg(
	ctx context.Context,
	request client.OptExperimentalConsoleSwitchOrgReq,
	params client.ExperimentalConsoleSwitchOrgParams,
	options ...client.RequestOption,
) (bool, error) {
	return Extract[bool](a.Client.ExperimentalConsoleSwitchOrg(ctx, request, params, options...))
}

// ExperimentalProjectCopyGenerateName invokes experimental.projectCopy.generateName operation.
//
// Generate a short name for a project copy from task context.
//
// POST /experimental/project/{projectID}/copy/generate-name
func (a *API) ExperimentalProjectCopyGenerateName(
	ctx context.Context,
	request client.OptExperimentalProjectCopyGenerateNameReq,
	params client.ExperimentalProjectCopyGenerateNameParams,
	options ...client.RequestOption,
) (*client.ExperimentalProjectCopyGenerateNameOK, error) {
	return Extract[*client.ExperimentalProjectCopyGenerateNameOK](a.Client.ExperimentalProjectCopyGenerateName(ctx, request, params, options...))
}

// ExperimentalResourceList invokes experimental.resource.list operation.
//
// Get all available MCP resources from connected servers. Optionally filter by name.
//
// GET /experimental/resource
func (a *API) ExperimentalResourceList(
	ctx context.Context,
	params client.ExperimentalResourceListParams,
	options ...client.RequestOption,
) (*client.ExperimentalResourceListOK, error) {
	return Extract[*client.ExperimentalResourceListOK](a.Client.ExperimentalResourceList(ctx, params, options...))
}

// ExperimentalSessionList invokes experimental.session.list operation.
//
// Get a list of all OpenCode sessions across projects, sorted by most recently updated. Archived
// sessions are excluded by default.
//
// GET /experimental/session
func (a *API) ExperimentalSessionList(
	ctx context.Context,
	params client.ExperimentalSessionListParams,
	options ...client.RequestOption,
) ([]client.GlobalSession, error) {
	res, err := Extract[*client.ExperimentalSessionListOKApplicationJSON](a.Client.ExperimentalSessionList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.GlobalSession(*res), nil
}

// ExperimentalWorkspaceAdapterList invokes experimental.workspace.adapter.list operation.
//
// List all available workspace adapters for the current project.
//
// GET /experimental/workspace/adapter
func (a *API) ExperimentalWorkspaceAdapterList(
	ctx context.Context,
	params client.ExperimentalWorkspaceAdapterListParams,
	options ...client.RequestOption,
) ([]client.ExperimentalWorkspaceAdapterListOKItem, error) {
	res, err := Extract[*client.ExperimentalWorkspaceAdapterListOKApplicationJSON](a.Client.ExperimentalWorkspaceAdapterList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.ExperimentalWorkspaceAdapterListOKItem(*res), nil
}

// ExperimentalWorkspaceStatus invokes experimental.workspace.status operation.
//
// Get connection status for workspaces in the current project.
//
// GET /experimental/workspace/status
func (a *API) ExperimentalWorkspaceStatus(
	ctx context.Context,
	params client.ExperimentalWorkspaceStatusParams,
	options ...client.RequestOption,
) ([]client.WorkspaceEventConnectionStatus, error) {
	res, err := Extract[*client.ExperimentalWorkspaceStatusOKApplicationJSON](a.Client.ExperimentalWorkspaceStatus(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.WorkspaceEventConnectionStatus(*res), nil
}

// ExperimentalWorkspaceSyncList invokes experimental.workspace.syncList operation.
//
// Register missing workspaces returned by workspace adapters.
//
// POST /experimental/workspace/sync-list
func (a *API) ExperimentalWorkspaceSyncList(
	ctx context.Context,
	params client.ExperimentalWorkspaceSyncListParams,
	options ...client.RequestOption,
) (client.ExperimentalWorkspaceSyncListRes, error) {
	return Extract[client.ExperimentalWorkspaceSyncListRes](a.Client.ExperimentalWorkspaceSyncList(ctx, params, options...))
}

// FileList invokes file.list operation.
//
// List files and directories in a specified path.
//
// GET /file
func (a *API) FileList(
	ctx context.Context,
	params client.FileListParams,
	options ...client.RequestOption,
) ([]client.FileNode, error) {
	res, err := Extract[*client.FileListOKApplicationJSON](a.Client.FileList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.FileNode(*res), nil
}

// FileRead invokes file.read operation.
//
// Read the content of a specified file.
//
// GET /file/content
func (a *API) FileRead(
	ctx context.Context,
	params client.FileReadParams,
	options ...client.RequestOption,
) (*client.FileContent, error) {
	return Extract[*client.FileContent](a.Client.FileRead(ctx, params, options...))
}

// FileStatus invokes file.status operation.
//
// Get the git status of all files in the project.
//
// GET /file/status
func (a *API) FileStatus(
	ctx context.Context,
	params client.FileStatusParams,
	options ...client.RequestOption,
) ([]client.File, error) {
	res, err := Extract[*client.FileStatusOKApplicationJSON](a.Client.FileStatus(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.File(*res), nil
}

// FindFiles invokes find.files operation.
//
// Search for files or directories by name or pattern in the project directory.
//
// GET /find/file
func (a *API) FindFiles(
	ctx context.Context,
	params client.FindFilesParams,
	options ...client.RequestOption,
) ([]string, error) {
	res, err := Extract[*client.FindFilesOKApplicationJSON](a.Client.FindFiles(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []string(*res), nil
}

// FindSymbols invokes find.symbols operation.
//
// Search for workspace symbols like functions, classes, and variables using LSP.
//
// GET /find/symbol
func (a *API) FindSymbols(
	ctx context.Context,
	params client.FindSymbolsParams,
	options ...client.RequestOption,
) ([]client.Symbol, error) {
	res, err := Extract[*client.FindSymbolsOKApplicationJSON](a.Client.FindSymbols(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Symbol(*res), nil
}

// FindText invokes find.text operation.
//
// Search for text patterns across files in the project using ripgrep.
//
// GET /find
func (a *API) FindText(
	ctx context.Context,
	params client.FindTextParams,
	options ...client.RequestOption,
) ([]client.FindTextOKItem, error) {
	res, err := Extract[*client.FindTextOKApplicationJSON](a.Client.FindText(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.FindTextOKItem(*res), nil
}

// FormatterStatus invokes formatter.status operation.
//
// Get formatter status.
//
// GET /formatter
func (a *API) FormatterStatus(
	ctx context.Context,
	params client.FormatterStatusParams,
	options ...client.RequestOption,
) ([]client.FormatterStatus, error) {
	res, err := Extract[*client.FormatterStatusOKApplicationJSON](a.Client.FormatterStatus(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.FormatterStatus(*res), nil
}

// GlobalDispose invokes global.dispose operation.
//
// Clean up and dispose all OpenCode instances, releasing all resources.
//
// POST /global/dispose
func (a *API) GlobalDispose(
	ctx context.Context,
	options ...client.RequestOption,
) (*client.GlobalDisposeOKApplicationJSON, error) {
	return Extract[*client.GlobalDisposeOKApplicationJSON](a.Client.GlobalDispose(ctx, options...))
}

// GlobalHealth invokes global.health operation.
//
// Get health information about the OpenCode server.
//
// GET /global/health
func (a *API) GlobalHealth(
	ctx context.Context,
	options ...client.RequestOption,
) (*client.GlobalHealthOK, error) {
	return Extract[*client.GlobalHealthOK](a.Client.GlobalHealth(ctx, options...))
}

// InstanceDispose invokes instance.dispose operation.
//
// Clean up and dispose the current OpenCode instance, releasing all resources.
//
// POST /instance/dispose
func (a *API) InstanceDispose(
	ctx context.Context,
	params client.InstanceDisposeParams,
	options ...client.RequestOption,
) (*client.InstanceDisposeOKApplicationJSON, error) {
	return Extract[*client.InstanceDisposeOKApplicationJSON](a.Client.InstanceDispose(ctx, params, options...))
}

// LspStatus invokes lsp.status operation.
//
// Get LSP server status.
//
// GET /lsp
func (a *API) LspStatus(
	ctx context.Context,
	params client.LspStatusParams,
	options ...client.RequestOption,
) ([]client.LSPStatus, error) {
	res, err := Extract[*client.LspStatusOKApplicationJSON](a.Client.LspStatus(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.LSPStatus(*res), nil
}

// McpAuthRemove invokes mcp.auth.remove operation.
//
// Remove OAuth credentials for an MCP server.
//
// DELETE /mcp/{name}/auth
func (a *API) McpAuthRemove(
	ctx context.Context,
	params client.McpAuthRemoveParams,
	options ...client.RequestOption,
) (*client.McpAuthRemoveOK, error) {
	return Extract[*client.McpAuthRemoveOK](a.Client.McpAuthRemove(ctx, params, options...))
}

// McpConnect invokes mcp.connect operation.
//
// Connect an MCP server.
//
// POST /mcp/{name}/connect
func (a *API) McpConnect(
	ctx context.Context,
	params client.McpConnectParams,
	options ...client.RequestOption,
) (*client.McpConnectOKApplicationJSON, error) {
	return Extract[*client.McpConnectOKApplicationJSON](a.Client.McpConnect(ctx, params, options...))
}

// McpDisconnect invokes mcp.disconnect operation.
//
// Disconnect an MCP server.
//
// POST /mcp/{name}/disconnect
func (a *API) McpDisconnect(
	ctx context.Context,
	params client.McpDisconnectParams,
	options ...client.RequestOption,
) (*client.McpDisconnectOKApplicationJSON, error) {
	return Extract[*client.McpDisconnectOKApplicationJSON](a.Client.McpDisconnect(ctx, params, options...))
}

// PathGet invokes path.get operation.
//
// Retrieve the current working directory and related path information for the OpenCode instance.
//
// GET /path
func (a *API) PathGet(
	ctx context.Context,
	params client.PathGetParams,
	options ...client.RequestOption,
) (*client.Path, error) {
	return Extract[*client.Path](a.Client.PathGet(ctx, params, options...))
}

// PermissionList invokes permission.list operation.
//
// Get all pending permission requests across all sessions.
//
// GET /permission
func (a *API) PermissionList(
	ctx context.Context,
	params client.PermissionListParams,
	options ...client.RequestOption,
) ([]client.PermissionRequest, error) {
	res, err := Extract[*client.PermissionListOKApplicationJSON](a.Client.PermissionList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.PermissionRequest(*res), nil
}

// ProjectCurrent invokes project.current operation.
//
// Retrieve the currently active project that OpenCode is working with.
//
// GET /project/current
func (a *API) ProjectCurrent(
	ctx context.Context,
	params client.ProjectCurrentParams,
	options ...client.RequestOption,
) (*client.Project, error) {
	return Extract[*client.Project](a.Client.ProjectCurrent(ctx, params, options...))
}

// ProjectDirectories invokes project.directories operation.
//
// List known local absolute directories for a project.
//
// GET /project/{projectID}/directories
func (a *API) ProjectDirectories(
	ctx context.Context,
	params client.ProjectDirectoriesParams,
	options ...client.RequestOption,
) ([]client.ProjectDirectoriesItem, error) {
	res, err := Extract[*client.ProjectDirectories](a.Client.ProjectDirectories(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.ProjectDirectoriesItem(*res), nil
}

// ProjectInitGit invokes project.initGit operation.
//
// Create a git repository for the current project and return the refreshed project info.
//
// POST /project/git/init
func (a *API) ProjectInitGit(
	ctx context.Context,
	params client.ProjectInitGitParams,
	options ...client.RequestOption,
) (*client.Project, error) {
	return Extract[*client.Project](a.Client.ProjectInitGit(ctx, params, options...))
}

// ProjectList invokes project.list operation.
//
// Get a list of projects that have been opened with OpenCode.
//
// GET /project
func (a *API) ProjectList(
	ctx context.Context,
	params client.ProjectListParams,
	options ...client.RequestOption,
) ([]client.Project, error) {
	res, err := Extract[*client.ProjectListOKApplicationJSON](a.Client.ProjectList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Project(*res), nil
}

// ProviderList invokes provider.list operation.
//
// Get a list of all available AI providers, including both available and connected ones.
//
// GET /provider
func (a *API) ProviderList(
	ctx context.Context,
	params client.ProviderListParams,
	options ...client.RequestOption,
) (*client.ProviderListOK, error) {
	return Extract[*client.ProviderListOK](a.Client.ProviderList(ctx, params, options...))
}

// PtyConnect invokes pty.connect operation.
//
// Establish a WebSocket connection to interact with a pseudo-terminal (PTY) session in real-time.
//
// GET /pty/{ptyID}/connect
func (a *API) PtyConnect(
	ctx context.Context,
	params client.PtyConnectParams,
	options ...client.RequestOption,
) (*client.PtyConnectOKApplicationJSON, error) {
	return Extract[*client.PtyConnectOKApplicationJSON](a.Client.PtyConnect(ctx, params, options...))
}

// PtyConnectToken invokes pty.connectToken operation.
//
// Create a short-lived ticket for opening a PTY WebSocket connection.
//
// POST /pty/{ptyID}/connect-token
func (a *API) PtyConnectToken(
	ctx context.Context,
	params client.PtyConnectTokenParams,
	options ...client.RequestOption,
) (*client.PtyTicketConnectToken, error) {
	return Extract[*client.PtyTicketConnectToken](a.Client.PtyConnectToken(ctx, params, options...))
}

// PtyGet invokes pty.get operation.
//
// Retrieve detailed information about a specific pseudo-terminal (PTY) session.
//
// GET /pty/{ptyID}
func (a *API) PtyGet(
	ctx context.Context,
	params client.PtyGetParams,
	options ...client.RequestOption,
) (*client.Pty, error) {
	return Extract[*client.Pty](a.Client.PtyGet(ctx, params, options...))
}

// PtyList invokes pty.list operation.
//
// Get a list of all active pseudo-terminal (PTY) sessions managed by OpenCode.
//
// GET /pty
func (a *API) PtyList(
	ctx context.Context,
	params client.PtyListParams,
	options ...client.RequestOption,
) ([]client.Pty, error) {
	res, err := Extract[*client.PtyListOKApplicationJSON](a.Client.PtyList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Pty(*res), nil
}

// PtyRemove invokes pty.remove operation.
//
// Remove and terminate a specific pseudo-terminal (PTY) session.
//
// DELETE /pty/{ptyID}
func (a *API) PtyRemove(
	ctx context.Context,
	params client.PtyRemoveParams,
	options ...client.RequestOption,
) (*client.PtyRemoveOKApplicationJSON, error) {
	return Extract[*client.PtyRemoveOKApplicationJSON](a.Client.PtyRemove(ctx, params, options...))
}

// PtyShells invokes pty.shells operation.
//
// Get a list of available shells on the system.
//
// GET /pty/shells
func (a *API) PtyShells(
	ctx context.Context,
	params client.PtyShellsParams,
	options ...client.RequestOption,
) ([]client.PtyShellsOKItem, error) {
	res, err := Extract[*client.PtyShellsOKApplicationJSON](a.Client.PtyShells(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.PtyShellsOKItem(*res), nil
}

// QuestionList invokes question.list operation.
//
// Get all pending question requests across all sessions.
//
// GET /question
func (a *API) QuestionList(
	ctx context.Context,
	params client.QuestionListParams,
	options ...client.RequestOption,
) ([]client.QuestionRequest, error) {
	res, err := Extract[*client.QuestionListOKApplicationJSON](a.Client.QuestionList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.QuestionRequest(*res), nil
}

// SessionDiff invokes session.diff operation.
//
// Get the file changes (diff) that resulted from a specific user message in the session.
//
// GET /session/{sessionID}/diff
func (a *API) SessionDiff(
	ctx context.Context,
	params client.SessionDiffParams,
	options ...client.RequestOption,
) ([]client.SnapshotFileDiff, error) {
	res, err := Extract[*client.SessionDiffOKApplicationJSON](a.Client.SessionDiff(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.SnapshotFileDiff(*res), nil
}

// SessionList invokes session.list operation.
//
// Get a list of all OpenCode sessions, sorted by most recently updated.
//
// GET /session
func (a *API) SessionList(
	ctx context.Context,
	params client.SessionListParams,
	options ...client.RequestOption,
) ([]client.Session, error) {
	res, err := Extract[*client.SessionListOKApplicationJSON](a.Client.SessionList(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.Session(*res), nil
}

// SessionShare invokes session.share operation.
//
// Create a shareable link for a session, allowing others to view the conversation.
//
// POST /session/{sessionID}/share
func (a *API) SessionShare(
	ctx context.Context,
	params client.SessionShareParams,
	options ...client.RequestOption,
) (*client.Session, error) {
	return Extract[*client.Session](a.Client.SessionShare(ctx, params, options...))
}

// SessionUnshare invokes session.unshare operation.
//
// Remove the shareable link for a session, making it private again.
//
// DELETE /session/{sessionID}/share
func (a *API) SessionUnshare(
	ctx context.Context,
	params client.SessionUnshareParams,
	options ...client.RequestOption,
) (*client.Session, error) {
	return Extract[*client.Session](a.Client.SessionUnshare(ctx, params, options...))
}

// SyncStart invokes sync.start operation.
//
// Start sync loops for workspaces in the current project that have active sessions.
//
// POST /sync/start
func (a *API) SyncStart(
	ctx context.Context,
	params client.SyncStartParams,
	options ...client.RequestOption,
) (*client.SyncStartOKApplicationJSON, error) {
	return Extract[*client.SyncStartOKApplicationJSON](a.Client.SyncStart(ctx, params, options...))
}

// TuiClearPrompt invokes tui.clearPrompt operation.
//
// Clear the prompt.
//
// POST /tui/clear-prompt
func (a *API) TuiClearPrompt(
	ctx context.Context,
	params client.TuiClearPromptParams,
	options ...client.RequestOption,
) (*client.TuiClearPromptOKApplicationJSON, error) {
	return Extract[*client.TuiClearPromptOKApplicationJSON](a.Client.TuiClearPrompt(ctx, params, options...))
}

// TuiControlNext invokes tui.control.next operation.
//
// Retrieve the next TUI request from the queue for processing.
//
// GET /tui/control/next
func (a *API) TuiControlNext(
	ctx context.Context,
	params client.TuiControlNextParams,
	options ...client.RequestOption,
) (*client.TuiControlNextOK, error) {
	return Extract[*client.TuiControlNextOK](a.Client.TuiControlNext(ctx, params, options...))
}

// TuiControlResponse invokes tui.control.response operation.
//
// Submit a response to the TUI request queue to complete a pending request.
//
// POST /tui/control/response
func (a *API) TuiControlResponse(
	ctx context.Context,
	request jx.Raw,
	params client.TuiControlResponseParams,
	options ...client.RequestOption,
) (*client.TuiControlResponseOKApplicationJSON, error) {
	return Extract[*client.TuiControlResponseOKApplicationJSON](a.Client.TuiControlResponse(ctx, request, params, options...))
}

// TuiOpenHelp invokes tui.openHelp operation.
//
// Open the help dialog in the TUI to display user assistance information.
//
// POST /tui/open-help
func (a *API) TuiOpenHelp(
	ctx context.Context,
	params client.TuiOpenHelpParams,
	options ...client.RequestOption,
) (*client.TuiOpenHelpOKApplicationJSON, error) {
	return Extract[*client.TuiOpenHelpOKApplicationJSON](a.Client.TuiOpenHelp(ctx, params, options...))
}

// TuiOpenModels invokes tui.openModels operation.
//
// Open the model dialog.
//
// POST /tui/open-models
func (a *API) TuiOpenModels(
	ctx context.Context,
	params client.TuiOpenModelsParams,
	options ...client.RequestOption,
) (*client.TuiOpenModelsOKApplicationJSON, error) {
	return Extract[*client.TuiOpenModelsOKApplicationJSON](a.Client.TuiOpenModels(ctx, params, options...))
}

// TuiOpenSessions invokes tui.openSessions operation.
//
// Open the session dialog.
//
// POST /tui/open-sessions
func (a *API) TuiOpenSessions(
	ctx context.Context,
	params client.TuiOpenSessionsParams,
	options ...client.RequestOption,
) (*client.TuiOpenSessionsOKApplicationJSON, error) {
	return Extract[*client.TuiOpenSessionsOKApplicationJSON](a.Client.TuiOpenSessions(ctx, params, options...))
}

// TuiOpenThemes invokes tui.openThemes operation.
//
// Open the theme dialog.
//
// POST /tui/open-themes
func (a *API) TuiOpenThemes(
	ctx context.Context,
	params client.TuiOpenThemesParams,
	options ...client.RequestOption,
) (*client.TuiOpenThemesOKApplicationJSON, error) {
	return Extract[*client.TuiOpenThemesOKApplicationJSON](a.Client.TuiOpenThemes(ctx, params, options...))
}

// TuiShowToast invokes tui.showToast operation.
//
// Show a toast notification in the TUI.
//
// POST /tui/show-toast
func (a *API) TuiShowToast(
	ctx context.Context,
	request client.OptTuiShowToastReq,
	params client.TuiShowToastParams,
	options ...client.RequestOption,
) (*client.TuiShowToastOKApplicationJSON, error) {
	return Extract[*client.TuiShowToastOKApplicationJSON](a.Client.TuiShowToast(ctx, request, params, options...))
}

// TuiSubmitPrompt invokes tui.submitPrompt operation.
//
// Submit the prompt.
//
// POST /tui/submit-prompt
func (a *API) TuiSubmitPrompt(
	ctx context.Context,
	params client.TuiSubmitPromptParams,
	options ...client.RequestOption,
) (*client.TuiSubmitPromptOKApplicationJSON, error) {
	return Extract[*client.TuiSubmitPromptOKApplicationJSON](a.Client.TuiSubmitPrompt(ctx, params, options...))
}

// V2CommandList invokes v2.command.list operation.
//
// Retrieve currently registered commands.
//
// GET /api/command
func (a *API) V2CommandList(
	ctx context.Context,
	params client.V2CommandListParams,
	options ...client.RequestOption,
) (*client.V2CommandListOK, error) {
	return Extract[*client.V2CommandListOK](a.Client.V2CommandList(ctx, params, options...))
}

// V2CredentialRemove invokes v2.credential.remove operation.
//
// Remove a stored integration credential.
//
// DELETE /api/credential/{credentialID}
func (a *API) V2CredentialRemove(
	ctx context.Context,
	params client.V2CredentialRemoveParams,
	options ...client.RequestOption,
) (client.V2CredentialRemoveRes, error) {
	return Extract[client.V2CredentialRemoveRes](a.Client.V2CredentialRemove(ctx, params, options...))
}

// V2CredentialUpdate invokes v2.credential.update operation.
//
// Update a stored credential label.
//
// PATCH /api/credential/{credentialID}
func (a *API) V2CredentialUpdate(
	ctx context.Context,
	request *client.V2CredentialUpdateReq,
	params client.V2CredentialUpdateParams,
	options ...client.RequestOption,
) (client.V2CredentialUpdateRes, error) {
	return Extract[client.V2CredentialUpdateRes](a.Client.V2CredentialUpdate(ctx, request, params, options...))
}

// V2FsFind invokes v2.fs.find operation.
//
// Find recursively ranked filesystem entries relative to the requested location.
//
// GET /api/fs/find
func (a *API) V2FsFind(
	ctx context.Context,
	params client.V2FsFindParams,
	options ...client.RequestOption,
) (*client.V2FsFindOK, error) {
	return Extract[*client.V2FsFindOK](a.Client.V2FsFind(ctx, params, options...))
}

// V2FsList invokes v2.fs.list operation.
//
// List direct children of one directory relative to the requested location.
//
// GET /api/fs/list
func (a *API) V2FsList(
	ctx context.Context,
	params client.V2FsListParams,
	options ...client.RequestOption,
) (*client.V2FsListOK, error) {
	return Extract[*client.V2FsListOK](a.Client.V2FsList(ctx, params, options...))
}

// V2FsRead invokes v2.fs.read operation.
//
// Serve one file relative to the requested location.
//
// GET /api/fs/read/*
func (a *API) V2FsRead(
	ctx context.Context,
	params client.V2FsReadParams,
	options ...client.RequestOption,
) (client.V2FsReadRes, error) {
	return Extract[client.V2FsReadRes](a.Client.V2FsRead(ctx, params, options...))
}

// V2HealthGet invokes v2.health.get operation.
//
// Check whether the API server is ready to accept requests.
//
// GET /api/health
func (a *API) V2HealthGet(
	ctx context.Context,
	options ...client.RequestOption,
) (*client.V2HealthGetOK, error) {
	return Extract[*client.V2HealthGetOK](a.Client.V2HealthGet(ctx, options...))
}

// V2IntegrationAttemptCancel invokes v2.integration.attempt.cancel operation.
//
// Cancel an OAuth attempt and release its resources.
//
// DELETE /api/integration/attempt/{attemptID}
func (a *API) V2IntegrationAttemptCancel(
	ctx context.Context,
	params client.V2IntegrationAttemptCancelParams,
	options ...client.RequestOption,
) (client.V2IntegrationAttemptCancelRes, error) {
	return Extract[client.V2IntegrationAttemptCancelRes](a.Client.V2IntegrationAttemptCancel(ctx, params, options...))
}

// V2LocationGet invokes v2.location.get operation.
//
// Resolve the requested location or the server default location.
//
// GET /api/location
func (a *API) V2LocationGet(
	ctx context.Context,
	params client.V2LocationGetParams,
	options ...client.RequestOption,
) (*client.LocationInfo, error) {
	return Extract[*client.LocationInfo](a.Client.V2LocationGet(ctx, params, options...))
}

// V2PermissionRequestList invokes v2.permission.request.list operation.
//
// Retrieve pending permission requests for a location.
//
// GET /api/permission/request
func (a *API) V2PermissionRequestList(
	ctx context.Context,
	params client.V2PermissionRequestListParams,
	options ...client.RequestOption,
) (*client.V2PermissionRequestListOK, error) {
	return Extract[*client.V2PermissionRequestListOK](a.Client.V2PermissionRequestList(ctx, params, options...))
}

// V2PermissionSavedList invokes v2.permission.saved.list operation.
//
// Retrieve saved permissions, optionally filtered by project.
//
// GET /api/permission/saved
func (a *API) V2PermissionSavedList(
	ctx context.Context,
	params client.V2PermissionSavedListParams,
	options ...client.RequestOption,
) (*client.V2PermissionSavedListOK, error) {
	return Extract[*client.V2PermissionSavedListOK](a.Client.V2PermissionSavedList(ctx, params, options...))
}

// V2PermissionSavedRemove invokes v2.permission.saved.remove operation.
//
// Remove a saved permission by ID.
//
// DELETE /api/permission/saved/{id}
func (a *API) V2PermissionSavedRemove(
	ctx context.Context,
	params client.V2PermissionSavedRemoveParams,
	options ...client.RequestOption,
) (client.V2PermissionSavedRemoveRes, error) {
	return Extract[client.V2PermissionSavedRemoveRes](a.Client.V2PermissionSavedRemove(ctx, params, options...))
}

// V2PtyConnect invokes v2.pty.connect operation.
//
// Establish a WebSocket connection streaming PTY output and accepting terminal input.
//
// GET /api/pty/{ptyID}/connect
func (a *API) V2PtyConnect(
	ctx context.Context,
	params client.V2PtyConnectParams,
	options ...client.RequestOption,
) (*client.V2PtyConnectOKApplicationJSON, error) {
	return Extract[*client.V2PtyConnectOKApplicationJSON](a.Client.V2PtyConnect(ctx, params, options...))
}

// V2PtyConnectToken invokes v2.pty.connectToken operation.
//
// Create a short-lived single-use ticket for opening a PTY WebSocket connection.
//
// POST /api/pty/{ptyID}/connect-token
func (a *API) V2PtyConnectToken(
	ctx context.Context,
	params client.V2PtyConnectTokenParams,
	options ...client.RequestOption,
) (*client.V2PtyConnectTokenOK, error) {
	return Extract[*client.V2PtyConnectTokenOK](a.Client.V2PtyConnectToken(ctx, params, options...))
}

// V2PtyCreate invokes v2.pty.create operation.
//
// Create a pseudo-terminal session for a location.
//
// POST /api/pty
func (a *API) V2PtyCreate(
	ctx context.Context,
	request *client.V2PtyCreateReq,
	params client.V2PtyCreateParams,
	options ...client.RequestOption,
) (*client.V2PtyCreateOK, error) {
	return Extract[*client.V2PtyCreateOK](a.Client.V2PtyCreate(ctx, request, params, options...))
}

// V2PtyGet invokes v2.pty.get operation.
//
// Get one PTY session, including its exit code once exited.
//
// GET /api/pty/{ptyID}
func (a *API) V2PtyGet(
	ctx context.Context,
	params client.V2PtyGetParams,
	options ...client.RequestOption,
) (*client.V2PtyGetOK, error) {
	return Extract[*client.V2PtyGetOK](a.Client.V2PtyGet(ctx, params, options...))
}

// V2PtyList invokes v2.pty.list operation.
//
// List PTY sessions for a location, including exited sessions retained until removal.
//
// GET /api/pty
func (a *API) V2PtyList(
	ctx context.Context,
	params client.V2PtyListParams,
	options ...client.RequestOption,
) (*client.V2PtyListOK, error) {
	return Extract[*client.V2PtyListOK](a.Client.V2PtyList(ctx, params, options...))
}

// V2PtyRemove invokes v2.pty.remove operation.
//
// Terminate and remove one PTY session.
//
// DELETE /api/pty/{ptyID}
func (a *API) V2PtyRemove(
	ctx context.Context,
	params client.V2PtyRemoveParams,
	options ...client.RequestOption,
) (client.V2PtyRemoveRes, error) {
	return Extract[client.V2PtyRemoveRes](a.Client.V2PtyRemove(ctx, params, options...))
}

// V2PtyUpdate invokes v2.pty.update operation.
//
// Update the title or viewport size of one PTY session.
//
// PUT /api/pty/{ptyID}
func (a *API) V2PtyUpdate(
	ctx context.Context,
	request *client.V2PtyUpdateReq,
	params client.V2PtyUpdateParams,
	options ...client.RequestOption,
) (*client.V2PtyUpdateOK, error) {
	return Extract[*client.V2PtyUpdateOK](a.Client.V2PtyUpdate(ctx, request, params, options...))
}

// V2QuestionRequestList invokes v2.question.request.list operation.
//
// Retrieve pending question requests for a location.
//
// GET /api/question/request
func (a *API) V2QuestionRequestList(
	ctx context.Context,
	params client.V2QuestionRequestListParams,
	options ...client.RequestOption,
) (*client.V2QuestionRequestListOK, error) {
	return Extract[*client.V2QuestionRequestListOK](a.Client.V2QuestionRequestList(ctx, params, options...))
}

// V2SessionActive invokes v2.session.active operation.
//
// Retrieve foreground Session drains currently owned by this OpenCode process. Sessions absent from
// the result are inactive.
//
// GET /api/session/active
func (a *API) V2SessionActive(
	ctx context.Context,
	options ...client.RequestOption,
) (*client.V2SessionActiveOK, error) {
	return Extract[*client.V2SessionActiveOK](a.Client.V2SessionActive(ctx, options...))
}

// V2SessionCreate invokes v2.session.create operation.
//
// Create a session at the requested location.
//
// POST /api/session
func (a *API) V2SessionCreate(
	ctx context.Context,
	request *client.V2SessionCreateReq,
	options ...client.RequestOption,
) (*client.V2SessionCreateOK, error) {
	return Extract[*client.V2SessionCreateOK](a.Client.V2SessionCreate(ctx, request, options...))
}

// V2SkillList invokes v2.skill.list operation.
//
// Retrieve currently registered skills.
//
// GET /api/skill
func (a *API) V2SkillList(
	ctx context.Context,
	params client.V2SkillListParams,
	options ...client.RequestOption,
) (*client.V2SkillListOK, error) {
	return Extract[*client.V2SkillListOK](a.Client.V2SkillList(ctx, params, options...))
}

// VcsDiff invokes vcs.diff operation.
//
// Retrieve the current git diff for the working tree or against the default branch.
//
// GET /vcs/diff
func (a *API) VcsDiff(
	ctx context.Context,
	params client.VcsDiffParams,
	options ...client.RequestOption,
) ([]client.VcsFileDiff, error) {
	res, err := Extract[*client.VcsDiffOKApplicationJSON](a.Client.VcsDiff(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.VcsFileDiff(*res), nil
}

// VcsDiffRaw invokes vcs.diff.raw operation.
//
// Retrieve a raw patch for current uncommitted changes.
//
// GET /vcs/diff/raw
func (a *API) VcsDiffRaw(
	ctx context.Context,
	params client.VcsDiffRawParams,
	options ...client.RequestOption,
) (client.VcsDiffRawRes, error) {
	return Extract[client.VcsDiffRawRes](a.Client.VcsDiffRaw(ctx, params, options...))
}

// VcsGet invokes vcs.get operation.
//
// Retrieve version control system (VCS) information for the current project, such as git branch.
//
// GET /vcs
func (a *API) VcsGet(
	ctx context.Context,
	params client.VcsGetParams,
	options ...client.RequestOption,
) (*client.VcsInfo, error) {
	return Extract[*client.VcsInfo](a.Client.VcsGet(ctx, params, options...))
}

// VcsStatus invokes vcs.status operation.
//
// Retrieve changed files in the current working tree without patches.
//
// GET /vcs/status
func (a *API) VcsStatus(
	ctx context.Context,
	params client.VcsStatusParams,
	options ...client.RequestOption,
) ([]client.VcsFileStatus, error) {
	res, err := Extract[*client.VcsStatusOKApplicationJSON](a.Client.VcsStatus(ctx, params, options...))
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return []client.VcsFileStatus(*res), nil
}
