# yaml-language-server: $schema=https://raw.githubusercontent.com/ogen-go/ogen/main/schemas/ogen.jsonschema.json

parser:
  infer_types: true # Helps safely decode ambiguous real-world specs

generator:
  ignore_not_implemented: ["all"]
  features:
    disable_all: true
    enable:
      - "paths/client"      # Generates outbound HTTP clients
      - "client/editors"    # Allows you to inject request middlewares
      - "client/request/options"