// Code generated by ogen, DO NOT EDIT.

package client

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes V2CommandListLocation as URI form.
func (s *V2CommandListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2CommandListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2CommandListLocation from URI form.
func (s *V2CommandListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2CommandListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2CommandListLocation")
	}

	return nil
}

// EncodeURI encodes V2CredentialRemoveLocation as URI form.
func (s *V2CredentialRemoveLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2CredentialRemoveLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2CredentialRemoveLocation from URI form.
func (s *V2CredentialRemoveLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2CredentialRemoveLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2CredentialRemoveLocation")
	}

	return nil
}

// EncodeURI encodes V2CredentialUpdateLocation as URI form.
func (s *V2CredentialUpdateLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2CredentialUpdateLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2CredentialUpdateLocation from URI form.
func (s *V2CredentialUpdateLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2CredentialUpdateLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2CredentialUpdateLocation")
	}

	return nil
}

// EncodeURI encodes V2FsFindLocation as URI form.
func (s *V2FsFindLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2FsFindLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2FsFindLocation from URI form.
func (s *V2FsFindLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2FsFindLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2FsFindLocation")
	}

	return nil
}

// EncodeURI encodes V2FsListLocation as URI form.
func (s *V2FsListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2FsListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2FsListLocation from URI form.
func (s *V2FsListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2FsListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2FsListLocation")
	}

	return nil
}

// EncodeURI encodes V2FsReadLocation as URI form.
func (s *V2FsReadLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2FsReadLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2FsReadLocation from URI form.
func (s *V2FsReadLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2FsReadLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2FsReadLocation")
	}

	return nil
}

// EncodeURI encodes V2IntegrationAttemptCancelLocation as URI form.
func (s *V2IntegrationAttemptCancelLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2IntegrationAttemptCancelLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2IntegrationAttemptCancelLocation from URI form.
func (s *V2IntegrationAttemptCancelLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2IntegrationAttemptCancelLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2IntegrationAttemptCancelLocation")
	}

	return nil
}

// EncodeURI encodes V2LocationGetLocation as URI form.
func (s *V2LocationGetLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2LocationGetLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2LocationGetLocation from URI form.
func (s *V2LocationGetLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2LocationGetLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2LocationGetLocation")
	}

	return nil
}

// EncodeURI encodes V2PermissionRequestListLocation as URI form.
func (s *V2PermissionRequestListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PermissionRequestListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PermissionRequestListLocation from URI form.
func (s *V2PermissionRequestListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PermissionRequestListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PermissionRequestListLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyConnectTokenLocation as URI form.
func (s *V2PtyConnectTokenLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyConnectTokenLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyConnectTokenLocation from URI form.
func (s *V2PtyConnectTokenLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyConnectTokenLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyConnectTokenLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyCreateLocation as URI form.
func (s *V2PtyCreateLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyCreateLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyCreateLocation from URI form.
func (s *V2PtyCreateLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyCreateLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyCreateLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyGetLocation as URI form.
func (s *V2PtyGetLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyGetLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyGetLocation from URI form.
func (s *V2PtyGetLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyGetLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyGetLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyListLocation as URI form.
func (s *V2PtyListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyListLocation from URI form.
func (s *V2PtyListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyListLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyRemoveLocation as URI form.
func (s *V2PtyRemoveLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyRemoveLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyRemoveLocation from URI form.
func (s *V2PtyRemoveLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyRemoveLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyRemoveLocation")
	}

	return nil
}

// EncodeURI encodes V2PtyUpdateLocation as URI form.
func (s *V2PtyUpdateLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2PtyUpdateLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2PtyUpdateLocation from URI form.
func (s *V2PtyUpdateLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2PtyUpdateLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2PtyUpdateLocation")
	}

	return nil
}

// EncodeURI encodes V2QuestionRequestListLocation as URI form.
func (s *V2QuestionRequestListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2QuestionRequestListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2QuestionRequestListLocation from URI form.
func (s *V2QuestionRequestListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2QuestionRequestListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2QuestionRequestListLocation")
	}

	return nil
}

// EncodeURI encodes V2SkillListLocation as URI form.
func (s *V2SkillListLocation) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("directory", func(e uri.Encoder) error {
		if val, ok := s.Directory.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"directory\"")
	}
	if err := e.EncodeField("workspace", func(e uri.Encoder) error {
		if val, ok := s.Workspace.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"workspace\"")
	}
	return nil
}

var uriFieldsNameOfV2SkillListLocation = [2]string{
	0: "directory",
	1: "workspace",
}

// DecodeURI decodes V2SkillListLocation from URI form.
func (s *V2SkillListLocation) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode V2SkillListLocation to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "directory":
			if err := func() error {
				var sDotDirectoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotDirectoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Directory.SetTo(sDotDirectoryVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"directory\"")
			}
		case "workspace":
			if err := func() error {
				var sDotWorkspaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotWorkspaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Workspace.SetTo(sDotWorkspaceVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"workspace\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode V2SkillListLocation")
	}

	return nil
}
