// Code generated by ogen, DO NOT EDIT.

package client

// AppAgentsParams is parameters of app.agents operation.
type AppAgentsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// AppSkillsParams is parameters of app.skills operation.
type AppSkillsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// CommandListParams is parameters of command.list operation.
type CommandListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ConfigProvidersParams is parameters of config.providers operation.
type ConfigProvidersParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalCapabilitiesGetParams is parameters of experimental.capabilities.get operation.
type ExperimentalCapabilitiesGetParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalConsoleGetParams is parameters of experimental.console.get operation.
type ExperimentalConsoleGetParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalConsoleListOrgsParams is parameters of experimental.console.listOrgs operation.
type ExperimentalConsoleListOrgsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalConsoleSwitchOrgParams is parameters of experimental.console.switchOrg operation.
type ExperimentalConsoleSwitchOrgParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalProjectCopyGenerateNameParams is parameters of experimental.projectCopy.generateName operation.
type ExperimentalProjectCopyGenerateNameParams struct {
	ProjectID string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalResourceListParams is parameters of experimental.resource.list operation.
type ExperimentalResourceListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalSessionListParams is parameters of experimental.session.list operation.
type ExperimentalSessionListParams struct {
	Directory OptString                          `json:",omitempty,omitzero"`
	Workspace OptString                          `json:",omitempty,omitzero"`
	Roots     OptExperimentalSessionListRoots    `json:",omitempty,omitzero"`
	Start     OptFloat64                         `json:",omitempty,omitzero"`
	Cursor    OptFloat64                         `json:",omitempty,omitzero"`
	Search    OptString                          `json:",omitempty,omitzero"`
	Limit     OptFloat64                         `json:",omitempty,omitzero"`
	Archived  OptExperimentalSessionListArchived `json:",omitempty,omitzero"`
}

// ExperimentalWorkspaceAdapterListParams is parameters of experimental.workspace.adapter.list operation.
type ExperimentalWorkspaceAdapterListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalWorkspaceStatusParams is parameters of experimental.workspace.status operation.
type ExperimentalWorkspaceStatusParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ExperimentalWorkspaceSyncListParams is parameters of experimental.workspace.syncList operation.
type ExperimentalWorkspaceSyncListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// FileListParams is parameters of file.list operation.
type FileListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Path      string
}

// FileReadParams is parameters of file.read operation.
type FileReadParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Path      string
}

// FileStatusParams is parameters of file.status operation.
type FileStatusParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// FindFilesParams is parameters of find.files operation.
type FindFilesParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Query     string
	Dirs      OptFindFilesDirs `json:",omitempty,omitzero"`
	Type      OptFindFilesType `json:",omitempty,omitzero"`
	Limit     OptInt           `json:",omitempty,omitzero"`
}

// FindSymbolsParams is parameters of find.symbols operation.
type FindSymbolsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Query     string
}

// FindTextParams is parameters of find.text operation.
type FindTextParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Pattern   string
}

// FormatterStatusParams is parameters of formatter.status operation.
type FormatterStatusParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// InstanceDisposeParams is parameters of instance.dispose operation.
type InstanceDisposeParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// LspStatusParams is parameters of lsp.status operation.
type LspStatusParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// McpAuthRemoveParams is parameters of mcp.auth.remove operation.
type McpAuthRemoveParams struct {
	Name      string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// McpConnectParams is parameters of mcp.connect operation.
type McpConnectParams struct {
	Name      string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// McpDisconnectParams is parameters of mcp.disconnect operation.
type McpDisconnectParams struct {
	Name      string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PathGetParams is parameters of path.get operation.
type PathGetParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PermissionListParams is parameters of permission.list operation.
type PermissionListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ProjectCurrentParams is parameters of project.current operation.
type ProjectCurrentParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ProjectDirectoriesParams is parameters of project.directories operation.
type ProjectDirectoriesParams struct {
	ProjectID string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ProjectInitGitParams is parameters of project.initGit operation.
type ProjectInitGitParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ProjectListParams is parameters of project.list operation.
type ProjectListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// ProviderListParams is parameters of provider.list operation.
type ProviderListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PtyConnectParams is parameters of pty.connect operation.
type PtyConnectParams struct {
	PtyID     string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Cursor    OptString `json:",omitempty,omitzero"`
	Ticket    OptString `json:",omitempty,omitzero"`
}

// PtyConnectTokenParams is parameters of pty.connectToken operation.
type PtyConnectTokenParams struct {
	PtyID     string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PtyGetParams is parameters of pty.get operation.
type PtyGetParams struct {
	PtyID     string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PtyListParams is parameters of pty.list operation.
type PtyListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PtyRemoveParams is parameters of pty.remove operation.
type PtyRemoveParams struct {
	PtyID     string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// PtyShellsParams is parameters of pty.shells operation.
type PtyShellsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// QuestionListParams is parameters of question.list operation.
type QuestionListParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// SessionDiffParams is parameters of session.diff operation.
type SessionDiffParams struct {
	SessionID string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	MessageID OptString `json:",omitempty,omitzero"`
}

// SessionListParams is parameters of session.list operation.
type SessionListParams struct {
	Directory OptString           `json:",omitempty,omitzero"`
	Workspace OptString           `json:",omitempty,omitzero"`
	Scope     OptSessionListScope `json:",omitempty,omitzero"`
	Path      OptString           `json:",omitempty,omitzero"`
	Roots     OptSessionListRoots `json:",omitempty,omitzero"`
	Start     OptFloat64          `json:",omitempty,omitzero"`
	Search    OptString           `json:",omitempty,omitzero"`
	Limit     OptFloat64          `json:",omitempty,omitzero"`
}

// SessionShareParams is parameters of session.share operation.
type SessionShareParams struct {
	SessionID string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// SessionUnshareParams is parameters of session.unshare operation.
type SessionUnshareParams struct {
	SessionID string
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// SyncStartParams is parameters of sync.start operation.
type SyncStartParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiClearPromptParams is parameters of tui.clearPrompt operation.
type TuiClearPromptParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiControlNextParams is parameters of tui.control.next operation.
type TuiControlNextParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiControlResponseParams is parameters of tui.control.response operation.
type TuiControlResponseParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiOpenHelpParams is parameters of tui.openHelp operation.
type TuiOpenHelpParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiOpenModelsParams is parameters of tui.openModels operation.
type TuiOpenModelsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiOpenSessionsParams is parameters of tui.openSessions operation.
type TuiOpenSessionsParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiOpenThemesParams is parameters of tui.openThemes operation.
type TuiOpenThemesParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiShowToastParams is parameters of tui.showToast operation.
type TuiShowToastParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// TuiSubmitPromptParams is parameters of tui.submitPrompt operation.
type TuiSubmitPromptParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// V2CommandListParams is parameters of v2.command.list operation.
type V2CommandListParams struct {
	Location OptV2CommandListLocation `json:",omitempty,omitzero"`
}

// V2CredentialRemoveParams is parameters of v2.credential.remove operation.
type V2CredentialRemoveParams struct {
	CredentialID string
	Location     OptV2CredentialRemoveLocation `json:",omitempty,omitzero"`
}

// V2CredentialUpdateParams is parameters of v2.credential.update operation.
type V2CredentialUpdateParams struct {
	CredentialID string
	Location     OptV2CredentialUpdateLocation `json:",omitempty,omitzero"`
}

// V2FsFindParams is parameters of v2.fs.find operation.
type V2FsFindParams struct {
	Location OptV2FsFindLocation `json:",omitempty,omitzero"`
	Query    string
	Type     OptV2FsFindType `json:",omitempty,omitzero"`
	Limit    OptString       `json:",omitempty,omitzero"`
}

// V2FsListParams is parameters of v2.fs.list operation.
type V2FsListParams struct {
	Location OptV2FsListLocation `json:",omitempty,omitzero"`
	Path     OptString           `json:",omitempty,omitzero"`
}

// V2FsReadParams is parameters of v2.fs.read operation.
type V2FsReadParams struct {
	Location OptV2FsReadLocation `json:",omitempty,omitzero"`
}

// V2IntegrationAttemptCancelParams is parameters of v2.integration.attempt.cancel operation.
type V2IntegrationAttemptCancelParams struct {
	AttemptID string
	Location  OptV2IntegrationAttemptCancelLocation `json:",omitempty,omitzero"`
}

// V2LocationGetParams is parameters of v2.location.get operation.
type V2LocationGetParams struct {
	Location OptV2LocationGetLocation `json:",omitempty,omitzero"`
}

// V2PermissionRequestListParams is parameters of v2.permission.request.list operation.
type V2PermissionRequestListParams struct {
	Location OptV2PermissionRequestListLocation `json:",omitempty,omitzero"`
}

// V2PermissionSavedListParams is parameters of v2.permission.saved.list operation.
type V2PermissionSavedListParams struct {
	ProjectID OptString `json:",omitempty,omitzero"`
}

// V2PermissionSavedRemoveParams is parameters of v2.permission.saved.remove operation.
type V2PermissionSavedRemoveParams struct {
	ID string
}

// V2PtyConnectParams is parameters of v2.pty.connect operation.
type V2PtyConnectParams struct {
	PtyID             string
	LocationDirectory OptString `json:",omitempty,omitzero"`
	LocationWorkspace OptString `json:",omitempty,omitzero"`
	Cursor            OptString `json:",omitempty,omitzero"`
	Ticket            OptString `json:",omitempty,omitzero"`
}

// V2PtyConnectTokenParams is parameters of v2.pty.connectToken operation.
type V2PtyConnectTokenParams struct {
	PtyID    string
	Location OptV2PtyConnectTokenLocation `json:",omitempty,omitzero"`
}

// V2PtyCreateParams is parameters of v2.pty.create operation.
type V2PtyCreateParams struct {
	Location OptV2PtyCreateLocation `json:",omitempty,omitzero"`
}

// V2PtyGetParams is parameters of v2.pty.get operation.
type V2PtyGetParams struct {
	PtyID    string
	Location OptV2PtyGetLocation `json:",omitempty,omitzero"`
}

// V2PtyListParams is parameters of v2.pty.list operation.
type V2PtyListParams struct {
	Location OptV2PtyListLocation `json:",omitempty,omitzero"`
}

// V2PtyRemoveParams is parameters of v2.pty.remove operation.
type V2PtyRemoveParams struct {
	PtyID    string
	Location OptV2PtyRemoveLocation `json:",omitempty,omitzero"`
}

// V2PtyUpdateParams is parameters of v2.pty.update operation.
type V2PtyUpdateParams struct {
	PtyID    string
	Location OptV2PtyUpdateLocation `json:",omitempty,omitzero"`
}

// V2QuestionRequestListParams is parameters of v2.question.request.list operation.
type V2QuestionRequestListParams struct {
	Location OptV2QuestionRequestListLocation `json:",omitempty,omitzero"`
}

// V2SkillListParams is parameters of v2.skill.list operation.
type V2SkillListParams struct {
	Location OptV2SkillListLocation `json:",omitempty,omitzero"`
}

// VcsDiffParams is parameters of vcs.diff operation.
type VcsDiffParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
	Mode      VcsDiffMode
	Context   OptInt `json:",omitempty,omitzero"`
}

// VcsDiffRawParams is parameters of vcs.diff.raw operation.
type VcsDiffRawParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// VcsGetParams is parameters of vcs.get operation.
type VcsGetParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}

// VcsStatusParams is parameters of vcs.status operation.
type VcsStatusParams struct {
	Directory OptString `json:",omitempty,omitzero"`
	Workspace OptString `json:",omitempty,omitzero"`
}
