// Code generated by ogen, DO NOT EDIT.
package client

type AppAgentsRes interface {
	appAgentsRes()
}

type AppSkillsRes interface {
	appSkillsRes()
}

type CommandListRes interface {
	commandListRes()
}

type ConfigProvidersRes interface {
	configProvidersRes()
}

type ExperimentalCapabilitiesGetRes interface {
	experimentalCapabilitiesGetRes()
}

type ExperimentalConsoleGetRes interface {
	experimentalConsoleGetRes()
}

type ExperimentalConsoleListOrgsRes interface {
	experimentalConsoleListOrgsRes()
}

type ExperimentalProjectCopyGenerateNameRes interface {
	experimentalProjectCopyGenerateNameRes()
}

type ExperimentalResourceListRes interface {
	experimentalResourceListRes()
}

type ExperimentalSessionListRes interface {
	experimentalSessionListRes()
}

type ExperimentalWorkspaceAdapterListRes interface {
	experimentalWorkspaceAdapterListRes()
}

type ExperimentalWorkspaceStatusRes interface {
	experimentalWorkspaceStatusRes()
}

type ExperimentalWorkspaceSyncListRes interface {
	experimentalWorkspaceSyncListRes()
}

type FileListRes interface {
	fileListRes()
}

type FileReadRes interface {
	fileReadRes()
}

type FileStatusRes interface {
	fileStatusRes()
}

type FindFilesRes interface {
	findFilesRes()
}

type FindSymbolsRes interface {
	findSymbolsRes()
}

type FindTextRes interface {
	findTextRes()
}

type FormatterStatusRes interface {
	formatterStatusRes()
}

type GlobalDisposeRes interface {
	globalDisposeRes()
}

type GlobalHealthRes interface {
	globalHealthRes()
}

type InstanceDisposeRes interface {
	instanceDisposeRes()
}

type LspStatusRes interface {
	lspStatusRes()
}

type McpAuthRemoveRes interface {
	mcpAuthRemoveRes()
}

type McpConnectRes interface {
	mcpConnectRes()
}

type McpDisconnectRes interface {
	mcpDisconnectRes()
}

type PathGetRes interface {
	pathGetRes()
}

type PermissionListRes interface {
	permissionListRes()
}

type ProjectCurrentRes interface {
	projectCurrentRes()
}

type ProjectDirectoriesRes interface {
	projectDirectoriesRes()
}

type ProjectInitGitRes interface {
	projectInitGitRes()
}

type ProjectListRes interface {
	projectListRes()
}

type ProviderListRes interface {
	providerListRes()
}

type PtyConnectRes interface {
	ptyConnectRes()
}

type PtyConnectTokenRes interface {
	ptyConnectTokenRes()
}

type PtyGetRes interface {
	ptyGetRes()
}

type PtyListRes interface {
	ptyListRes()
}

type PtyRemoveRes interface {
	ptyRemoveRes()
}

type PtyShellsRes interface {
	ptyShellsRes()
}

type QuestionListRes interface {
	questionListRes()
}

type SessionDiffRes interface {
	sessionDiffRes()
}

type SessionListRes interface {
	sessionListRes()
}

type SessionShareRes interface {
	sessionShareRes()
}

type SessionUnshareRes interface {
	sessionUnshareRes()
}

type SyncStartRes interface {
	syncStartRes()
}

type TuiClearPromptRes interface {
	tuiClearPromptRes()
}

type TuiControlNextRes interface {
	tuiControlNextRes()
}

type TuiControlResponseRes interface {
	tuiControlResponseRes()
}

type TuiOpenHelpRes interface {
	tuiOpenHelpRes()
}

type TuiOpenModelsRes interface {
	tuiOpenModelsRes()
}

type TuiOpenSessionsRes interface {
	tuiOpenSessionsRes()
}

type TuiOpenThemesRes interface {
	tuiOpenThemesRes()
}

type TuiShowToastRes interface {
	tuiShowToastRes()
}

type TuiSubmitPromptRes interface {
	tuiSubmitPromptRes()
}

type V2CommandListRes interface {
	v2CommandListRes()
}

type V2CredentialRemoveRes interface {
	v2CredentialRemoveRes()
}

type V2CredentialUpdateRes interface {
	v2CredentialUpdateRes()
}

type V2FsFindRes interface {
	v2FsFindRes()
}

type V2FsListRes interface {
	v2FsListRes()
}

type V2FsReadRes interface {
	v2FsReadRes()
}

type V2HealthGetRes interface {
	v2HealthGetRes()
}

type V2IntegrationAttemptCancelRes interface {
	v2IntegrationAttemptCancelRes()
}

type V2LocationGetRes interface {
	v2LocationGetRes()
}

type V2PermissionRequestListRes interface {
	v2PermissionRequestListRes()
}

type V2PermissionSavedListRes interface {
	v2PermissionSavedListRes()
}

type V2PermissionSavedRemoveRes interface {
	v2PermissionSavedRemoveRes()
}

type V2PtyConnectRes interface {
	v2PtyConnectRes()
}

type V2PtyConnectTokenRes interface {
	v2PtyConnectTokenRes()
}

type V2PtyCreateRes interface {
	v2PtyCreateRes()
}

type V2PtyGetRes interface {
	v2PtyGetRes()
}

type V2PtyListRes interface {
	v2PtyListRes()
}

type V2PtyRemoveRes interface {
	v2PtyRemoveRes()
}

type V2PtyUpdateRes interface {
	v2PtyUpdateRes()
}

type V2QuestionRequestListRes interface {
	v2QuestionRequestListRes()
}

type V2SessionActiveRes interface {
	v2SessionActiveRes()
}

type V2SessionCreateRes interface {
	v2SessionCreateRes()
}

type V2SkillListRes interface {
	v2SkillListRes()
}

type VcsDiffRawRes interface {
	vcsDiffRawRes()
}

type VcsDiffRes interface {
	vcsDiffRes()
}

type VcsGetRes interface {
	vcsGetRes()
}

type VcsStatusRes interface {
	vcsStatusRes()
}
